### ISSUE TITLE
Drag & Drop failing in firefox

### ISSUE THREAD

**Issue by javatlacati** [jpillora/base64-encoder#2]
As you can see in the image D&D is not working properly on firefox perhaps it's a javascript issue.

![firefox](https://cloud.githubusercontent.com/assets/1063901/7374828/243d24e8-ed9a-11e4-90c7-d53ab3123622.png)

**Comment by jpillora** [comment]
Works for me in `37.0.2`

![screen shot 2015-04-29 at 12 20 02 pm](https://cloud.githubusercontent.com/assets/633843/7383855/33dfa396-ee6a-11e4-8721-2a52cfcf8303.png)

**Comment by javatlacati** [comment]
It's a bug from the firefox developer "edition". Some JS doesn't work on that modified version of the popular browser.
